### ISSUE TITLE
Number of commands tripled from migration from WsClientBundle

### ISSUE THREAD

**Issue by mikaelrandy** [M6Web/GuzzleHttpBundle#7]
We have just deployed migration from WsClientBundle to GuzzleHttpBundle on one of our services, and we notice a major increase of Redis commands executed : 

![image](https://cloud.githubusercontent.com/assets/187703/8719317/0db4916c-2bab-11e5-880d-1ead943ecb44.png)

For each `GET` command, there is an `EXISTS` and `TTL` command execution.
The code responsible of it is [here](https://github.com/M6Web/GuzzleHttpBundle/blob/master/src/Handler/CacheTrait.php#L115-L131)

2 questions : 
* is it mandatory to call `EXISTS` before `GET` ?
* is the `TLL` call ever mandatory, even in non-dev env ?

**Comment by mojoLyon** [comment]
The `exists` method is call through the `has` method defined in `CacheInterface` and implemented in adapter in the redis bundle.
This is mandatory because we can have a null value set in cache system, so we need to test if the key is set instead of testing if the retrieved values is null.

For the ttl call you're right, this should be call only in dev environment.
